# Generated by Django 6.0 on 2025-12-24 17:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=255, unique=True, verbose_name='Kanal ID')),
                ('channel_username', models.CharField(max_length=255, verbose_name='Kanal username (@siz)')),
                ('title', models.CharField(max_length=255, verbose_name='Kanal nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqt")),
            ],
            options={
                'verbose_name': 'Kanal',
                'verbose_name_plural': 'Kanallar',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tuman nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Tuman',
                'verbose_name_plural': 'Tumanlar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Viloyat nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Viloyat',
                'verbose_name_plural': 'Viloyatlar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq ism")),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqam')),
                ('is_subscribed', models.BooleanField(default=False, verbose_name="Obuna bo'lganmi")),
                ('has_voted', models.BooleanField(default=False, verbose_name='Ovoz berganmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan vaqt")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Telegram foydalanuvchi',
                'verbose_name_plural': 'Telegram foydalanuvchilar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq ism")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidates/', verbose_name='Rasm')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biografiya')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lavozim')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqt")),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='api.district', verbose_name='Tuman')),
            ],
            options={
                'verbose_name': 'Nomzod',
                'verbose_name_plural': 'Nomzodlar',
                'ordering': ['order', 'full_name'],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='api.region', verbose_name='Viloyat'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('region', 'name')},
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ovoz berilgan vaqt')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.candidate', verbose_name='Nomzod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.telegramuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Ovoz',
                'verbose_name_plural': 'Ovozlar',
                'ordering': ['-voted_at'],
                'unique_together': {('user', 'candidate')},
            },
        ),
    ]
