# Generated by Django 6.0 on 2025-12-24 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="So'rovnoma nomi")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': "So'rovnoma",
                'verbose_name_plural': "So'rovnomalar",
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='has_voted',
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Viloyat nomi'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='region',
            name='poll',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='api.poll', verbose_name="So'rovnoma"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='poll',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.poll', verbose_name="So'rovnoma"),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('poll', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'poll')},
        ),
    ]
